### ISSUE TITLE
[bug] Public Registry not populated

### ISSUE THREAD

**Issue by GeorgeWL** [codemod-com/intuita-vscode-extension#830]
> :warning: Use this to report bugs related to the Intuita VS Code extension, not codemod-specific issues and improvements. For codemod-specific issues, please [submit an issue in the codemod registry](https://github.com/intuita-inc/codemod-registry/issues).

### Describe the bug

The public registry doesn't show any results

### Steps to Reproduce

1. Go to Intuita viewlet

2. Click on 'Codemod Discovery'

3. See no results

Search for 'msw'

See no results

### Actual behavior

Public registry shows no results

### Expected behavior

Public registry shows results

### Environment:
 - Intuita extension version: 0.36.16
 - OS: Windows 10 Enterprise, build number 19045.3693
 - Node.js version: 20.10.0

**Comment by MattyBalaam** [comment]
Hmm, I’ve just installed the extension and I am seeing the same issue 6 weeks later… is this project maintained?

**Comment by mohab-sameh** [comment]
@MattyBalaam Yes, we have a ticket opened for this. I'll make sure to have it prioritized ASAP. Thanks for re-activating this issue, Matty.

**Comment by DmytroHryshyn** [comment]
@MattyBalaam We already debugged the issue and planning to add Windows support during current sprint.

**Comment by mohab-sameh** [comment]
@MattyBalaam Windows support is now available in [v0.38.10](https://github.com/codemod-com/intuita-vscode-extension/releases/tag/v0.38.10) 🎉

**Comment by alexbit-codemod** [comment]
thanks @GeorgeWL for reporting this issue. please let us know if you come across any issues with our CLI or extension.
